url: "https://recipesformum.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Recipes for Mum" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss
  - jekyll-minifier
collections:
  recipes:
    output: true
    permalink: /:collection/:name
    order:
      - week-6.md
      - week-5.md
      - week-4.md
      - week-3.md
      - week-2.md
      - week-1.md